# SQLFlow Phase 2 Integration Demo Profile
# Docker environment configuration for testing with real services

name: "phase2_integration_demo"
version: "1.0"

# Environment configuration
environment: "docker"
debug: true
log_level: "INFO"

# Database configuration (DuckDB for local processing)
database:
  type: "duckdb"
  path: "/app/target/demo.duckdb"
  memory_limit: "2GB"
  threads: 4

# Connector configurations
connectors:
  postgres:
    type: "postgres"
    host: "postgres"
    port: 5432
    database: "demo"
    username: "sqlflow"
    password: "sqlflow123"
    schema: "public"
    sslmode: "prefer"
    connect_timeout: 30
    pool_size: 5
    
  s3:
    type: "s3"
    endpoint_url: "http://minio:9000"
    access_key_id: "minioadmin"
    secret_access_key: "minioadmin"
    region: "us-east-1"
    bucket: "sqlflow-demo"
    use_ssl: false
    cost_limit_usd: 10.0
    
# Variable definitions
variables:
  # Demo data paths
  data_dir: "/app/data"
  output_dir: "/app/output"
  
  # Date variables for incremental loading
  start_date: "2024-01-01"
  end_date: "2024-12-31"
  
  # Demo configuration
  demo_mode: true
  benchmark_mode: true
  
  # PostgreSQL connection details (for reference)
  postgres_host: "postgres"
  postgres_database: "demo"
  postgres_username: "sqlflow"
  postgres_password: "sqlflow123"
  
  # S3/MinIO connection details
  s3_endpoint: "http://minio:9000"
  s3_bucket: "sqlflow-demo"
  s3_access_key: "minioadmin"
  s3_secret_key: "minioadmin"

# Performance settings
performance:
  batch_size: 1000
  max_memory_mb: 2048
  parallel_workers: 2
  
# Logging configuration
logging:
  level: "INFO"
  format: "structured"
  output: "console"
  include_performance_metrics: true
  
# Testing configuration
testing:
  enabled: true
  data_validation: true
  performance_benchmarks: true
  error_simulation: false 