# SQLFlow Ecommerce Demo - Local Profile
# Use this profile for local development (in-memory DuckDB, fast, ephemeral)

engines:
  duckdb:
    mode: persistent
    path: "ecommerce.db"

variables:
  date: ${DATE}
  API_TOKEN: ${API_TOKEN}
  DB_CONN: "postgresql://sqlflow:sqlflow123@localhost:5432/ecommerce"

connectors:
  postgres:
    type: POSTGRES
    params:
      host: "localhost"
      port: 5432
      dbname: "ecommerce"
      user: "sqlflow"
      password: "sqlflow123"
  s3:
    type: S3
    params:
      endpoint_url: "http://localhost:9000"
      region: "us-east-1"
      access_key_id: "minioadmin"
      secret_access_key: "minioadmin"
      bucket: "analytics"
  rest:
    type: REST
    params:
      base_url: "http://localhost:1080"
      auth_method: "bearer"
      auth_params:
        token: "${API_TOKEN}"
  csv:
    type: CSV
    params:
      has_header: true 