# SQLFlow Ecommerce Demo - Production Profile
# Use this profile for production (persistent DuckDB, data saved to disk)

engines:
  duckdb:
    mode: persistent
    path: target/ecommerce_demo_prod.db
    memory_limit: 8GB

variables:
  date: ${DATE}
  API_TOKEN: ${API_TOKEN}
  DB_CONN: "postgresql://sqlflow:sqlflow123@postgres:5432/ecommerce"
  env: "production"

connectors:
  postgres:
    type: POSTGRES
    params:
      host: "postgres"
      port: 5432
      dbname: "ecommerce"
      user: "sqlflow"
      password: "sqlflow123"
  s3:
    type: S3
    params:
      endpoint_url: "http://minio:9000"
      region: "us-east-1"
      access_key_id: "minioadmin"
      secret_access_key: "minioadmin"
      bucket: "analytics"
  rest:
    type: REST
    params:
      base_url: "http://mockserver:1080"
      auth_method: "bearer"
      auth_params:
        token: "${API_TOKEN}" 