name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install networkx
          pip install -e .[dev]

      - name: Lint with autoflake
        run: |
          autoflake --in-place --remove-all-unused-imports --remove-unused-variables --expand-star-imports --ignore-init-module-imports .

      - name: Format with black
        run: |
          black .

      - name: Sort imports with isort
        run: |
          isort --profile black .

      - name: Lint with flake8
        run: |
          flake8 --ignore=E501,E221,E222,E223,E224,E303,E301,E302,E402,F401,F841,E741,W291,W293,D100,D101,W503,W504,E203 --max-complexity=10 .

      - name: Run tests
        run: |
          pytest -q --maxfail=5 --disable-warnings --cov=sqlflow
          COVERAGE=$(pytest --cov=sqlflow --cov-report=xml | grep TOTAL | awk '{print $4}' | sed 's/%//')
          echo "Test coverage: $COVERAGE%"
          if [ "$COVERAGE" -lt 80 ]; then
            echo "Test coverage below target (< 80%)"
            echo "::warning::Test coverage is below 80%. Current coverage: $COVERAGE%"
          fi
