name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install networkx
          pip install -e .[dev]

      - name: Check code style
        run: |
          black --check .
          isort --check-only .
          flake8 --config=setup.cfg .

      - name: Run tests
        run: |
          pytest --cov=sqlflow
          COVERAGE=$(pytest --cov=sqlflow --cov-report=xml | grep TOTAL | awk '{print $4}' | sed 's/%//')
          echo "Test coverage: $COVERAGE%"
          if [ "$COVERAGE" -lt 80 ]; then
            echo "Test coverage below target (< 80%)"
            echo "::warning::Test coverage is below 80%. Current coverage: $COVERAGE%"
          fi
