name: CI

on:
  push:
    branches: [ main, dev ]
    paths:
      - '**.py'
      - 'tests/**'
      - 'setup.py'
      - 'setup.cfg'
      - 'pyproject.toml'
      - 'requirements*.txt'
      - '.github/workflows/ci.yml'
      - 'examples/**'
  pull_request:
    branches: [ main, dev ]
    paths:
      - '**.py'
      - 'tests/**'
      - 'setup.py'
      - 'setup.cfg'
      - 'pyproject.toml'
      - 'requirements*.txt'
      - '.github/workflows/ci.yml'
      - 'examples/**'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']

    steps: 
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install networkx
          pip install -e .[dev]

      - name: Run ruff linting
        run: |
          ruff check --fix --exit-non-zero-on-fix .

      - name: Run ruff formatting
        run: |
          ruff format .

      - name: Run tests with coverage (parallel)
        run: |
          pytest --cov=sqlflow --cov-branch --cov-report=xml -n auto --dist worksteal --maxfail=3

      - name: Run example demo scripts
        run: |
          chmod +x ./run_all_examples.sh
          ./run_all_examples.sh

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true 
          verbose: true