name: CI

on:
  push:
    branches: [ main, dev ]
    paths:
      - '**.py'
      - 'tests/**'
      - 'setup.py'
      - 'setup.cfg'
      - 'pyproject.toml'
      - 'requirements*.txt'
      - '.github/workflows/ci.yml'
      - 'examples/**'
  pull_request:
    branches: [ main, dev ]
    paths:
      - '**.py'
      - 'tests/**'
      - 'setup.py'
      - 'setup.cfg'
      - 'pyproject.toml'
      - 'requirements*.txt'
      - '.github/workflows/ci.yml'
      - 'examples/**'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']

    steps: 
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[all]

      - name: Run autoflake
        run: |
          autoflake --in-place --remove-all-unused-imports --remove-unused-variables --expand-star-imports --ignore-init-module-imports --recursive .

      - name: Run black formatting
        run: |
          black .

      - name: Run isort
        run: |
          isort --profile black .

      - name: Run flake8 linting
        run: |
          flake8 --ignore=E501,E221,E222,E223,E224,E303,E301,E302,E402,F401,F841,E741,W291,W293,D100,D101,W503,W504,E203 --max-complexity=10 .

      - name: Run tests with coverage (parallel)
        run: |
          pytest --cov=sqlflow --cov-branch --cov-report=xml -n auto --dist worksteal --maxfail=3 -q --disable-warnings

      - name: Run example demo scripts
        run: |
          chmod +x ./run_all_examples.sh
          ./run_all_examples.sh

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true 
          verbose: true